### ISSUE TITLE
Crash on subscribe

### ISSUE THREAD

**Issue by sevenbitbyte** [transcendrobotics/zed_cpu_ros#4] opened 2017-06-09 21:08 UTC
When I attempt to subscribe to most stereo_image_proc topics it crashes with the below error:

```
process[camera/stereo_image_proc-3]: started with pid [24665]
OpenCV Error: Assertion failed (_map1.size().area() > 0) in remap, file /tmp/binarydeb/ros-kinetic-opencv3-3.2.0/modules/imgproc/src/imgwarp.cpp, line 4936
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.2.0/modules/imgproc/src/imgwarp.cpp:4936: error: (-215) _map1.size().area() > 0 in function remap
```

Are there additional system setup requirements to get this working? Any pointers on getting a better root cause?

**Comment by willdzeng** [comment] 2017-06-10 03:24
I had this problem before, mostly caused by bad calibration, you should try to use ROS's calibration package to calibrate the ZED first. The default ZED calibration parameter might not work directly with ROS.

Try use: zed_cpu_ros/launch/camera_calibration.launch

**Comment by andre-nguyen** [comment] 2017-06-15 17:05
If you use the ROS calibration and write it to left.yaml and right.yaml you have to set `load_zed_config` to `false` in the launch file.

**Comment by sevenbitbyte** [comment] 2017-06-15 18:56
Awesome I'll give this a try

**Comment by willdzeng** [comment] 2018-04-07 18:21
is this still an issue?

**Comment by hmchung** [comment] 2018-04-08 14:29
@willdzeng, I faced the same issue. Calibration seems to help.

By the way, thank you for sharing this code. In order to make it more user friendly, I have added some default calibration configs and made some minor modification to the code. I have made a pull request to you. 

I hope beginners can just use this repo with their ZED out of the box.

**Comment by willdzeng** [comment] 2018-04-09 05:55
because different cameras will have different calibration parameters, it will be impossible that they can just run this out-of-box. Instead, if using ZED's default parameter is broken, we should try to fix it.

**Comment by willdzeng** [comment] 2018-04-16 05:43
I will try again and fix loading the zed config, will close this since you guys are able to use the ROS calibration file without issue.

**Closed as completed by willdzeng** 2018-04-16 05:43 UTC
